openapi: 3.0.1
info:
  title: WhatsApp API
  description: API for interacting with WhatsApp REST API
  version: 1.1.0
servers:
- url: https://localhost:3000/api
- url: http://localhost:3000/api
paths:
  /ping:
    get:
      tags:
      - Health
      summary: Check if server is alive
      description: Send a Ping and expect a pong back
      responses:
        200:
          description: Successful pong
          content:
            '*/*':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: pong
        500:
          description: Internal server error
          content: {}
  /api/qr/{number}:
    get:
      tags:
      - Authentication
      summary: Get QR code for login
      description: Retrieves a QR code for logging into WhatsApp
      parameters:
      - name: number
        in: path
        description: Phone number associated with the WhatsApp client Session
        required: true
        schema:
          type: string
      responses:
        200:
          description: QR code retrieved successfully
          content:
            '*/*':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: QR Requested successfully
        403:
          description: Invalid API key
          content: {}
        500:
          description: Internal server error
          content: {}
      callbacks:   # Callback definition
        QR Callback:   # Event name
          'https://example.com/webhook':   # The callback URL,
            post:
              requestBody:   # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        data_type:
                          type: string
                          example: qr
                        data:
                          type: string
                          example: 2@Q6BscIpaaVmpl8ddgpI0DUSQMcP71oX0mKJegCom1Yiry4dCWZrVV8OxZ917LZcf1Zx0+bwMNw5BDw==,htHiC8fWm3TBniiPh59lRXDhSygVMTREjD1WpdHRzwM=,OJ1Zgh051s66AgjxtL8gPEHQPs4LKU9m4T0sbuh/wCs=
                        number:
                          type: string
                          example: 6281288888888
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
        Status Callback:   # Event name
          'https://example.com/webhook':   # The callback URL,
            post:
              requestBody:   # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        data_type:
                          type: string
                          example: status
                        data:
                          type: string
                          example: authenticated
                        number:
                          type: string
                          example: 6281288888888
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
      security:
      - apiKey: []
  /api/sendMessage/{number}:
    post:
      tags:
      - Actions
      summary: Send a message
      description: Endpoint for sending a message
      parameters:
      - name: number
        in: path
        description: Phone number
        required: true
        schema:
          type: string
      requestBody:
        description: Request body for sending a message
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
        required: true
      responses:
        200:
          description: Success
          content: {}
        404:
          description: Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      callbacks:   # Callback definition
        New Message:   # Event name
          'https://example.com/webhook':   # The callback URL,
            post:
              requestBody:   # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        data_type:
                          type: string
                          example: message
                        data:
                          type: object
                          example: {"ack":1,"author":"62812999999999@c.us","body":"Hello World!","from":"120363098565083901@g.us","timestamp":1681275495,"to":"6281288888888@c.us"}
                        number:
                          type: string
                          example: 6281288888888
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
      x-codegen-request-body-name: body
  /api/validateNumber/{number}:
    post:
      tags:
      - Actions
      summary: Validate a number
      parameters:
      - name: number
        in: path
        description: Phone number to validate
        required: true
        schema:
          type: string
      requestBody:
        description: Request body for sending a message
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ValidateNumberRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            '*/*':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  valid:
                    type: boolean
        403:
          description: Invalid API key
          content: {}
        404:
          description: Number validation failed
          content: {}
        500:
          description: Internal server error
          content: {}
      security:
      - apiKey: []
      x-codegen-request-body-name: body
  /api/logout/{number}:
    get:
      tags:
      - Authentication
      summary: Log out a client session
      parameters:
      - name: number
        in: path
        description: Phone number of the session to log out
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            '*/*':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        403:
          description: Invalid API key
          content: {}
        404:
          description: Client session not found
          content: {}
        500:
          description: Internal server error
          content: {}
      security:
      - apiKey: []
components:
  schemas:
    SendMessageRequest:
      required:
      - message
      - target_number
      type: object
      properties:
        target_number:
          type: string
          description: Target number to send the message
        message:
          type: string
          description: Message to be sent
    ValidateNumberRequest:
      required:
      - target_number
      type: object
      properties:
        target_number:
          type: string
          description: Target number to send the message
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
